name: Ping Release event

on:
  push:
    branches:
    - 'release/*'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Hello World
      run: |
        echo "Hello World at ${{ github.ref_name }}"
